/*  layout.tsx */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { hygraph } from "@/lib/hygraph";
import {
  HOME_PAGE_QUERY,
  type HomePageQueryResult,
} from "@/lib/queries/home";

async function getHome() {
  const data = await hygraph.request<HomePageQueryResult>(HOME_PAGE_QUERY);
  return data.homePages[0];
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { const home = await getHome(); // 👈 QUI
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <ThemeProvider>
            {children}</ThemeProvider>
          </body>
    </html>
  );
}
